version: '2'
services:
    apadinhe-app:
        image: apadinhe
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://apadinhe-mysql:3306/apadinhe?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=apadinhe-elasticsearch:9300
        ports:
            - 8080:8080
    apadinhe-mysql:
        extends:
            file: mysql.yml
            service: apadinhe-mysql
    apadinhe-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: apadinhe-elasticsearch
